/* Job Control and Batch - JCL, JES2/JES3, abends, return codes */
window.MF_CODES = [
  { code: "S0C1", title: "OPERATION EXCEPTION", category: "SYSTEM ABEND", severity: "ERROR",
    description: "An operation exception was detected — the program tried to execute an invalid machine instruction.",
    cause: "Branched to an area without valid code (zeros, data, deleted load module). Often caused by stale module pointer or overlay of executable code.",
    fix: "Check the PSW and offset in the abend dump. Verify the program was linked correctly and the entry point exists. Check for storage overlays.",
    example: "PSW at abend: 078D1000 80001234\n*> Branched into a CSECT of zeros at offset X'1234'" },
  { code: "S0C4", title: "PROTECTION EXCEPTION", category: "SYSTEM ABEND", severity: "ERROR",
    description: "The program attempted to access storage it is not authorized to read or write.",
    cause: "Reference through an uninitialized or invalid pointer, walking off the end of an array, or accessing storage from a different key.",
    fix: "Look at the PSW and failing instruction in the IPCS dump. Trace the pointer back to where it was set.",
    example: "MVC  DEST,0(R3)     *> R3 contains X'00000000' from cleared field" },
  { code: "S0C7", title: "DATA EXCEPTION", category: "SYSTEM ABEND", severity: "ERROR",
    description: "A decimal arithmetic instruction encountered invalid packed-decimal or zoned-decimal data.",
    cause: "An input field contained spaces, low-values, or non-numeric characters where COBOL expected a numeric value. Common after reading uninitialized records.",
    fix: "Use NUMERIC test on COMP-3 inputs before arithmetic, or initialize fields to zero. Check the dump for failing instruction (AP, ZAP, CP, etc.) and the contents of the operands.",
    example: "01 WS-AMT PIC S9(7)V99 COMP-3.\n*> File field contained spaces -> ADD fails with S0C7." },
  { code: "S0C6", title: "SPECIFICATION EXCEPTION", category: "SYSTEM ABEND", severity: "ERROR",
    description: "The program executed an instruction with an invalid operand alignment or address.",
    cause: "Halfword/fullword/doubleword operand not aligned on required boundary, or odd-numbered register specified where even-odd pair is required.",
    fix: "Recompile with the correct alignment options. Check OPTIMIZE level and review the failing instruction.",
    example: "L R4,DATA      *> DATA defined as CL3, not aligned on fullword boundary" },
  { code: "S0CB", title: "DECIMAL DIVIDE EXCEPTION", category: "SYSTEM ABEND", severity: "ERROR",
    description: "A decimal divide instruction would have produced a quotient that does not fit in the destination, or the divisor was zero.",
    cause: "COMPUTE or DIVIDE statement where divisor is zero or the result is larger than the receiving field.",
    fix: "Test divisor for zero before dividing; expand the receiving field's size.",
    example: "DIVIDE A BY B GIVING C.\n*> B = ZERO -> S0CB" },
  { code: "S806", title: "MODULE NOT FOUND", category: "SYSTEM ABEND", severity: "ERROR",
    description: "The system could not find the requested load module in any library on the search order.",
    cause: "Module not linked, not in STEPLIB/JOBLIB/LINKLST, or wrong load library concatenation.",
    fix: "Verify the load module exists with the correct name and that the JCL points to the right STEPLIB. Check link-edit JCL for the correct member name.",
    example: "//STEPLIB DD DSN=MY.LOADLIB,DISP=SHR\n*> Module MYPGM not in MY.LOADLIB -> S806" },
  { code: "S813", title: "OPEN ERROR — DSNAME MISMATCH", category: "SYSTEM ABEND", severity: "ERROR",
    description: "An OPEN was issued against a data set whose name does not match what the program expects.",
    cause: "DCB name in the program doesn't match the DDname on tape volumes, or the wrong tape was mounted.",
    fix: "Verify the DDname and DSN. For tapes, check that the operator mounted the correct volume.",
    example: "//INFILE DD DSN=PROD.DATA  *> tape volume mismatched the DSN -> S813" },
  { code: "S322", title: "TIME LIMIT EXCEEDED", category: "SYSTEM ABEND", severity: "ERROR",
    description: "The job or step exceeded the CPU time limit specified on the JOB or EXEC card.",
    cause: "Long-running loop, missing index on Db2 access, or unexpectedly large input volume.",
    fix: "Increase TIME= parameter or tune the program. Add TIME=1440 for unlimited (use sparingly).",
    example: "//STEP1 EXEC PGM=BATCH,TIME=(0,30)\n*> 30 seconds CPU -> exceeded -> S322" },
  { code: "S722", title: "OUTPUT LIMIT EXCEEDED", category: "SYSTEM ABEND", severity: "ERROR",
    description: "The number of SYSOUT records produced by the job exceeded the installation limit.",
    cause: "Print loop, debug DISPLAY in production loop, or accidentally writing huge SYSOUT.",
    fix: "Trim print volume. If output volume is legitimate, raise OUTLIM on the DD or job class.",
    example: "//SYSPRINT DD SYSOUT=*,OUTLIM=10000\n*> exceeded 10000 lines -> S722" },
  { code: "S837", title: "OUT OF SECONDARY SPACE", category: "SYSTEM ABEND", severity: "ERROR",
    description: "A data set requires additional space but no more secondary extents are available.",
    cause: "Primary and 16 (or 123) secondary extents already allocated, or volume out of space.",
    fix: "Reallocate with larger primary/secondary, or REORG to compress. Use extended-format datasets for more extents.",
    example: "//OUTPUT DD DSN=BIG,SPACE=(CYL,(5,1))\n*> file grew beyond limit -> S837" },
  { code: "S913", title: "RACF SECURITY VIOLATION", category: "SYSTEM ABEND", severity: "ERROR",
    description: "Access to a data set or resource was denied by RACF.",
    cause: "User ID lacks READ/UPDATE/ALTER access to the data set, or the data set is protected with a different profile than expected.",
    fix: "Request access from the security admin, or use a generic profile that grants the needed access. Check ICH408I messages in JESYSMSG.",
    example: "ICH408I USER(USER1) GROUP(GRP) NAME(...)\n  ACCESS INTENT(UPDATE)  ACCESS ALLOWED(READ)" },
  { code: "U4038", title: "LE ABNORMAL TERMINATION", category: "USER ABEND", severity: "ERROR",
    description: "Language Environment terminated the application because an unhandled condition occurred (often raised by COBOL).",
    cause: "COBOL detected a condition (file status not 00, divide-by-zero, etc.) and LE was set to abend rather than continue.",
    fix: "Check the CEEDUMP for the failing condition token (e.g., CEE3204 for protection). Add condition handlers or correct the underlying error.",
    example: "CEE3204S The system detected a protection exception.\n*> Original error masked by U4038 wrapper" },
  { code: "U0016", title: "USER ABEND 16", category: "USER ABEND", severity: "ERROR",
    description: "A program-issued ABEND with completion code 16 — commonly used as a generic 'fatal error' code.",
    cause: "Application called ABEND or CEE3AB2 with code 16, usually because of a logical inconsistency the program chose to treat as fatal.",
    fix: "Locate the abend invocation point in the source; check the message preceding the abend for the actual reason.",
    example: "CALL 'CEE3AB2' USING 16 BY VALUE 0 RETURNING RC." },
  { code: "IEF212I", title: "DATA SET NOT FOUND", category: "JCL", severity: "ERROR",
    description: "The data set named on a DD statement could not be found in the catalog.",
    cause: "Misspelled DSN, missing catalog entry, or data set was uncataloged or deleted.",
    fix: "Verify the DSN spelling and ensure the data set exists with LISTC ENT(...).",
    example: "//INPUT DD DSN=MY.NONEXIST.FILE,DISP=SHR\nIEF212I JOB1 STEP1 INPUT - DATA SET NOT FOUND" },
  { code: "IEF285I", title: "DATA SET STATUS", category: "JCL", severity: "INFO",
    description: "Reports the disposition action taken on a data set at job step termination (CATALOGED, KEPT, DELETED, PASSED).",
    cause: "Issued for every DD with a disposition action; informational.",
    fix: "No action — for tracking only. If 'DELETED' was unexpected, check the DD's DISP for (NEW,DELETE,DELETE).",
    example: "IEF285I  MY.OUTPUT                                  CATALOGED\nIEF285I  VOL SER NOS= USR001." },
  { code: "IEF453I", title: "JCL ERROR", category: "JCL", severity: "ERROR",
    description: "A JCL syntax or semantic error prevented the job from running.",
    cause: "Misspelled keyword, missing operand, invalid value (e.g., SPACE=(CYL,-1)), or invalid data set name pattern.",
    fix: "Examine the IEFCxxx messages preceding IEF453I in the job log to see the exact JCL problem.",
    example: "IEFC630I  UNIDENTIFIED KEYWORD - SPCE\nIEF453I  JOB FAILED - JCL ERROR" },
  { code: "IEF642I", title: "INVALID KEYWORD VALUE", category: "JCL", severity: "ERROR",
    description: "A keyword on a JCL statement was supplied with an invalid value.",
    cause: "Wrong syntax in DISP, SPACE, DCB, or another DD parameter; value out of allowed range.",
    fix: "Refer to JCL Reference for valid syntax of the keyword.",
    example: "//OUTPUT DD DISP=(NEW,DELETE,CATLG)\nIEF642I  EXCESSIVE PARAMETER LENGTH IN THE DISP FIELD" },
  { code: "$HASP373", title: "JOB STARTED", category: "JES2", severity: "INFO",
    description: "JES2 informational message indicating a job has been initiated.",
    cause: "Job moved from input/conversion phase to execution.",
    fix: "Informational only. Use as a marker that the job started executing.",
    example: "$HASP373 MYJOB    STARTED - INIT 1   - CLASS A - SYS SY01" },
  { code: "$HASP395", title: "JOB ENDED", category: "JES2", severity: "INFO",
    description: "JES2 informational message indicating a job has completed, with its highest return code.",
    cause: "Job finished — either normally or by abend.",
    fix: "Read the maximum condition code or abend info shown to assess success/failure.",
    example: "$HASP395 MYJOB    ENDED - RC=0008" },
  { code: "$HASP050", title: "JES2 RESOURCE SHORTAGE", category: "JES2", severity: "WARNING",
    description: "JES2 has reached a resource shortage (spool, JOE, BERT, etc.).",
    cause: "Spool volumes getting full, too many active jobs holding output, or BERT/JOE limits hit.",
    fix: "Operator should free spool (purge old output) or operator should start more spool volumes.",
    example: "$HASP050 JES2 RESOURCE SHORTAGE OF SPOOL — 92% UTILIZATION" },
  { code: "IAT4801", title: "JES3 INVALID JCL", category: "JES3", severity: "ERROR",
    description: "JES3 detected invalid JCL during interpretation.",
    cause: "Syntax errors specific to JES3 //*MAIN, //*NET, or //*PROCESS statements.",
    fix: "Correct the JES3 control statement per JES3 commands reference.",
    example: "//*MAIN CLASS=A,SYSTEM=SY01\nIAT4801 INVALID OPERAND CLASS SY01" }
];
