/* DevOps, Testing and Debugging - Endevor, ChangeMan, IDz, File-AID, Xpediter */
window.MF_CODES = [
  { code: "C1G0023E", title: "ENDEVOR NOT APPROVED", category: "ENDEVOR", severity: "ERROR",
    description: "An Endevor action was rejected because a required approval is missing.",
    cause: "Element being moved requires manager approval, but no approval recorded.",
    fix: "Get the appropriate approver to approve the package, or check package status.",
    example: "C1G0023E PACKAGE PKG12345 NOT APPROVED FOR PROMOTION TO PROD" },
  { code: "C1G0410E", title: "ENDEVOR INVENTORY ERROR", category: "ENDEVOR", severity: "ERROR",
    description: "Endevor could not access or update an inventory element.",
    cause: "Element locked by another user, signed out, or inventory corruption.",
    fix: "Check element signout via QUERY ELEMENT; coordinate with the locker.",
    example: "C1G0410E ELEMENT PGM001 IS SIGNED-OUT BY USER2" },
  { code: "ENU013", title: "ENDEVOR USER ERROR", category: "ENDEVOR", severity: "ERROR",
    description: "User input or syntax error in an Endevor request.",
    cause: "Wrong type, environment, or stage in SCL.",
    fix: "Verify the SCL against the inventory structure (env, system, subsys, type).",
    example: "ENU013 TYPE 'COBL' NOT FOUND IN SYSTEM PROD" },
  { code: "CMN6304", title: "CHANGEMAN STAGE ERROR", category: "CHANGEMAN", severity: "ERROR",
    description: "ChangeMan ZMF cannot stage a component due to access or process violation.",
    cause: "Component checked out by another user, or wrong access level.",
    fix: "Check baseline/staging status; coordinate with the holder.",
    example: "CMN6304E COMPONENT MYPGM IS STAGED IN PACKAGE PROD-2025-001" },
  { code: "CMN0030", title: "CHANGEMAN PACKAGE NOT FOUND", category: "CHANGEMAN", severity: "ERROR",
    description: "Specified package does not exist.",
    cause: "Typo in package name, or package was deleted.",
    fix: "List packages via QUERY PACKAGE; correct the name.",
    example: "CMN0030E PACKAGE PROD-2025-099 DOES NOT EXIST" },
  { code: "AAUI001", title: "ABEND-AID FAULT CAPTURED", category: "ABEND-AID", severity: "INFO",
    description: "Compuware Abend-AID intercepted an abend and captured diagnostic data.",
    cause: "Application abended; Abend-AID exit triggered.",
    fix: "View the fault entry in Abend-AID for source-aware analysis.",
    example: "AAUI001I FAULT CAPTURED - JOB MYJOB STEP STEP1 ABEND S0C7" },
  { code: "FA0001", title: "FAULT ANALYZER REPORT", category: "FAULT ANALYZER", severity: "INFO",
    description: "IBM Fault Analyzer captured an abend and generated a real-time analysis report.",
    cause: "Application abended with Fault Analyzer exit active.",
    fix: "Open report in IDIUTIL or ISPF panels; trace cause section.",
    example: "FA0001 Real-time analysis report generated for JOB MYJOB" },
  { code: "FILEAID I/O ERR", title: "FILE-AID FILE ERROR", category: "FILE-AID", severity: "ERROR",
    description: "Compuware File-AID could not perform requested I/O operation.",
    cause: "Wrong layout assigned, file structure mismatch, or RACF block.",
    fix: "Verify the layout, check RACF, run File-AID extract/edit again.",
    example: "FILE-AID error: layout LAYOUT01 does not match input record length" },
  { code: "XPED ABEND", title: "XPEDITER BREAK", category: "XPEDITER", severity: "INFO",
    description: "Xpediter/TSO or Xpediter/CICS encountered a configured breakpoint or abend.",
    cause: "Programmed breakpoint, or watch condition matched in debugged code.",
    fix: "Use Xpediter primary commands to inspect storage and step through.",
    example: "XPED breakpoint hit at MYPGM offset X'0048' - line 124" },
  { code: "EQAU0100", title: "DEBUG TOOL ATTACH FAILED", category: "DEBUG TOOL", severity: "ERROR",
    description: "IBM Debug for z/OS could not attach to the application process.",
    cause: "Wrong CEEOPTS TEST settings, missing EQA load library, or session manager not available.",
    fix: "Check CEEOPTS TEST(...) value, ensure EQA load library on STEPLIB, verify session manager URL.",
    example: "EQAU0100E DEBUG TOOL ATTACH FAILED - SESSION MGR NOT REACHED" },
  { code: "IDz CRRZE003", title: "IDz WORKSPACE ERROR", category: "IDz", severity: "ERROR",
    description: "IBM Developer for z/OS reported a workspace or build error.",
    cause: "Connection lost to RSE, stale build artifacts, or local workspace corruption.",
    fix: "Reconnect to RSE; refresh resources; clean and rebuild project.",
    example: "CRRZE003E RSE connection lost to z/OS host PROD" },
  { code: "TT0001", title: "TOTAL TEST EXECUTION", category: "TOTAL TEST", severity: "INFO",
    description: "Topaz Total Test executed a test scenario.",
    cause: "Scheduled or on-demand test execution.",
    fix: "Informational; review results in Total Test dashboard.",
    example: "TT0001 TEST SCENARIO 'CUST_UPDATE_NEG' EXECUTED - PASSED" },
  { code: "Hiperstation HS001", title: "HIPERSTATION CAPTURE", category: "HIPERSTATION", severity: "INFO",
    description: "Compuware Hiperstation captured a 3270 session for replay/testing.",
    cause: "User initiated capture during interactive testing.",
    fix: "Informational; replay later for regression testing.",
    example: "HS001 SESSION CAPTURE STARTED - SESSION_ID=SES12345" },
  { code: "APAxxxx", title: "APA PROFILING ALERT", category: "APA", severity: "WARNING",
    description: "Application Performance Analyzer identified an outlier observation.",
    cause: "CPU spike, wait time anomaly, or unusual SVC activity in profiled job.",
    fix: "Open the APA report and inspect the hot module and call chain.",
    example: "APA: MODULE MYPGM CSECT MYCSECT - 45% CPU spent in offset X'0234'" },
  { code: "ChangeMan BLD12", title: "BUILD FAILED", category: "CHANGEMAN", severity: "ERROR",
    description: "Compile/link step for a staged component failed.",
    cause: "Source error, missing copybook, or RACF block on output library.",
    fix: "View build logs in ChangeMan; correct source and rebuild.",
    example: "CMN BLD12E COMPILE FAILED FOR COMPONENT MYPGM - RC=12" }
];
