/* Hardware, Virtualization and Disaster Recovery - Machine check, FICON, DASD, GDPS, z/VM */
window.MF_CODES = [
  { code: "IOS000I", title: "I/O ERROR", category: "I/O", severity: "ERROR",
    description: "z/OS Input/Output Supervisor detected an I/O error on a device.",
    cause: "Hardware failure, missing tape mount, control unit error, or cable problem.",
    fix: "Decode sense data shown; consult device vendor for the sense codes.",
    example: "IOS000I 0900,FF,IOE,02,0E00,,**,DSN,VOLSER\n  *> sense data X'FF03002B...'" },
  { code: "IOS002A", title: "MISSING INTERRUPT", category: "I/O", severity: "ERROR",
    description: "Operator must respond to a missing-interrupt condition.",
    cause: "Device did not present an interrupt in expected time; usually hung tape drive or stuck DASD.",
    fix: "Operator should respond, vary path offline if needed, then re-issue.",
    example: "IOS002A 0A00 MISSING INTERRUPT - REPLY N OR Y" },
  { code: "IOS050I", title: "LOGICAL CHANNEL RECOVERY", category: "FICON", severity: "WARNING",
    description: "FICON channel performed logical recovery on a failed I/O.",
    cause: "Transient channel/CU error recovered by the channel subsystem.",
    fix: "Informational unless recurring. Check OPER, IECIOSxx and CU diagnostics.",
    example: "IOS050I CHANNEL RECOVERY ON CHPID 24" },
  { code: "IGF11200I", title: "HARDWARE CONFIGURATION CHANGE", category: "HARDWARE", severity: "INFO",
    description: "z/OS detected a hardware configuration change (PR/SM, dynamic activate).",
    cause: "Dynamic I/O change via HCD, or LPAR config change.",
    fix: "Informational. Verify the change was expected.",
    example: "IGF11200I I/O CONFIGURATION CHANGE COMPLETE - LCU 0100 ADDED" },
  { code: "IGF10100I", title: "MACHINE CHECK", category: "HARDWARE", severity: "ERROR",
    description: "Hardware machine check reported by the processor.",
    cause: "Recoverable or unrecoverable hardware error; PRR, repeat-instruction, etc.",
    fix: "Capture LOGREC entry; report SE/HMC alert; engage IBM hardware support if recurring.",
    example: "IGF10100I MCH ICODE=00C0 PRR=01 CPU=03" },
  { code: "IOS125I", title: "MOUNT REQUIRED", category: "TAPE", severity: "INFO",
    description: "Operator must mount a specific tape volume.",
    cause: "Allocation requested a non-resident tape volume.",
    fix: "Operator mounts the volume on a drive; tape robot may auto-mount.",
    example: "IOS125I MOUNT TAP001 ON 0B00 FOR JOB MYJOB" },
  { code: "IOS451E", title: "DEVICE FAILED RECOVERY", category: "I/O", severity: "ERROR",
    description: "Channel subsystem could not recover the device after retries.",
    cause: "Hard hardware failure or persistent connectivity loss.",
    fix: "Vary device offline; engage hardware vendor.",
    example: "IOS451E DEVICE 0900 FAILED RECOVERY ATTEMPTS - VARIED OFFLINE" },
  { code: "HCPxxx", title: "z/VM HYPERVISOR MESSAGE", category: "z/VM", severity: "INFO",
    description: "z/VM CP issued a control program message (xxx is a 3-digit number).",
    cause: "Various — IPL, login, logoff, device, paging events.",
    fix: "Refer to z/VM CP Messages and Codes for the specific number.",
    example: "HCPCFC026E COMMAND SUSPENDED. RECONNECT TO COMPLETE." },
  { code: "DS8K SRC", title: "DS8000 REFERENCE CODE", category: "DASD ARRAY", severity: "ERROR",
    description: "IBM DS8000 system reference code (SRC) indicating array event.",
    cause: "Adapter card fault, rank failure, replication issue, or capacity threshold.",
    fix: "Use DS GUI; reference IBM DS8000 SRC database; call IBM if hardware replacement needed.",
    example: "DS8K SRC: BE8B - RANK ARRAY MEMBER REBUILD COMPLETED" },
  { code: "ICKDSF ERR", title: "ICKDSF INIT ERROR", category: "DASD UTIL", severity: "ERROR",
    description: "ICKDSF utility could not initialize, refresh, or analyze a volume.",
    cause: "Volume in use, wrong VOLID, or hardware issue blocking format.",
    fix: "Vary volume offline before INIT; verify VOLID; check device.",
    example: "ICKDSF: INIT FAILED ON VOL000 - VOLUME IN USE" },
  { code: "GDPS ALERT", title: "GDPS DISASTER RECOVERY EVENT", category: "GDPS", severity: "WARNING",
    description: "GDPS automation detected a site or system event requiring attention.",
    cause: "Cross-site PPRC issue, HyperSwap trigger, or planned freeze/swap event.",
    fix: "Open GDPS operator interface; follow procedure for the alert type.",
    example: "GDPS ALERT - PPRC SUSPEND DETECTED BETWEEN SITE1 AND SITE2" },
  { code: "HYPERSWAP TRIGGERED", title: "HYPERSWAP EVENT", category: "GDPS/HyperSwap", severity: "INFO",
    description: "HyperSwap performed an automatic swap to the secondary mirror.",
    cause: "Primary site DASD became unavailable; HyperSwap policy triggered swap.",
    fix: "Verify all volumes swapped; investigate primary site failure.",
    example: "HYPERSWAP COMPLETED - 24 LSS SWAPPED FROM SITE1 TO SITE2" },
  { code: "CHIT", title: "CHANNEL CONNECTION ERROR", category: "CHANNEL", severity: "ERROR",
    description: "Channel interface error reported by hardware.",
    cause: "Physical fiber cable disconnect, SFP failure, or switch issue.",
    fix: "Vary path offline; replace SFP/cable; reactivate.",
    example: "IOS150I CHPID 24 - INTERFACE ERROR (CHIT)" },
  { code: "PR/SM RESET", title: "LPAR RESET / DEACTIVATE", category: "PR/SM", severity: "WARNING",
    description: "PR/SM LPAR was reset or deactivated.",
    cause: "Operator action, hardware fault, or activation profile change.",
    fix: "Verify intent at HMC; review activation logs.",
    example: "HCPC107I LPAR PROD1 DEACTIVATED BY OPERATOR" },
  { code: "z/VM USER LOGON ERR", title: "VM LOGON ERROR", category: "z/VM", severity: "ERROR",
    description: "z/VM rejected a user logon attempt.",
    cause: "Invalid userid, wrong password, or directory entry locked.",
    fix: "Verify directory entry (DIRMAINT QUERY USER); reset password if needed.",
    example: "HCPLGA053E USERID NOT IN CP DIRECTORY" }
];
