/* Installation and Software Maintenance - SMP/E, APAR, PTF, HOLDDATA */
window.MF_CODES = [
  { code: "GIM23903E", title: "SYSMOD NOT RECEIVED", category: "SMP/E", severity: "ERROR",
    description: "APPLY or ACCEPT failed because the SYSMOD has not been RECEIVEd.",
    cause: "RECEIVE step skipped or failed; SYSMOD missing from SMPPTFIN.",
    fix: "RECEIVE FROMNTS or SOURCEID(...); then re-run APPLY.",
    example: "GIM23903E SYSMOD UO12345 IS NOT IN THE GLOBAL ZONE" },
  { code: "GIM27801E", title: "SYSMOD HELD", category: "SMP/E", severity: "ERROR",
    description: "APPLY or ACCEPT rejected because the SYSMOD has an outstanding HOLDDATA.",
    cause: "Internal HOLD reason or external HOLDDATA from PSP/ServiceLink.",
    fix: "Review HOLDDATA reason; if acceptable, BYPASS(HOLDSYSTEM,HOLDFIXCAT,...). Run REPORT MISSINGFIX first.",
    example: "GIM27801E SYSMOD UO45678 HAS HELD REASON ACTION - HIPER FIX REQUIRED" },
  { code: "GIM26801E", title: "MISSING PREREQ", category: "SMP/E", severity: "ERROR",
    description: "SYSMOD requires a prerequisite that is not yet installed.",
    cause: "Missing pre-req PTF, APAR, or co-req SYSMOD.",
    fix: "RECEIVE and APPLY the prereq first; or use BYPASS(REQ) carefully.",
    example: "GIM26801E SYSMOD UO12345 REQUIRES UO99999 WHICH IS NOT IN ZONE" },
  { code: "GIM44503W", title: "WARNING — CONDITION", category: "SMP/E", severity: "WARNING",
    description: "SMP/E completed with a warning condition (often missing PTFs noted in REPORT).",
    cause: "REPORT MISSINGFIX found gaps, or BYPASS used during APPLY.",
    fix: "Review the REPORT output and plan additional installs.",
    example: "GIM44503W APPLY COMPLETED WITH WARNINGS" },
  { code: "GIM50901I", title: "APPLY/ACCEPT COMPLETE", category: "SMP/E", severity: "INFO",
    description: "SMP/E completed APPLY or ACCEPT successfully.",
    cause: "Normal completion.",
    fix: "Informational; verify return code is 0 or 4.",
    example: "GIM50901I APPLY PROCESSING IS COMPLETE - HIGHEST RETURN CODE WAS 04" },
  { code: "GIM23801E", title: "ACCEPT ERROR", category: "SMP/E", severity: "ERROR",
    description: "ACCEPT command rejected because of zone state or missing prerequisites.",
    cause: "SYSMOD not APPLYd, or DLIB zone has missing function.",
    fix: "APPLY before ACCEPT. Check ZONEEDIT and DLIB content.",
    example: "GIM23801E SYSMOD UO12345 CANNOT BE ACCEPTED - NOT APPLIED" },
  { code: "GIM47802E", title: "MISSING HOLD ACTION", category: "SMP/E", severity: "ERROR",
    description: "An external HOLDDATA action item must be performed before installation can continue.",
    cause: "Documentation or operational HOLD pending — must be reviewed by human.",
    fix: "Read the HOLD reason, perform the action (job, IPL, parmlib change), then BYPASS that hold.",
    example: "GIM47802E HOLDDATA REQUIRES MANUAL ACTION FOR UO12345 (DOC)" },
  { code: "GIM35501T", title: "TERMINATION ERROR", category: "SMP/E", severity: "ERROR",
    description: "SMP/E task terminated due to severe error.",
    cause: "Read error on CSI, internal SMP/E error, or storage shortage.",
    fix: "Check job log for prior GIM messages; restart after corrective action.",
    example: "GIM35501T SMP/E PROCESSING TERMINATED ABNORMALLY" },
  { code: "GIM69139I", title: "RETURN CODE 4", category: "SMP/E", severity: "WARNING",
    description: "Step completed with non-zero but non-fatal return code.",
    cause: "Often: SYSMOD already installed, or warnings during install.",
    fix: "Inspect SMPRPT for details.",
    example: "GIM69139I APPLY ENDED WITH RETURN CODE 4 - SYSMODS ALREADY APPLIED" },
  { code: "GIM42801E", title: "DATA SET ALLOCATION FAILURE", category: "SMP/E", severity: "ERROR",
    description: "SMP/E could not allocate a needed data set (DLIB, target, work).",
    cause: "Missing DD, wrong DSN, or RACF blocked allocation.",
    fix: "Verify the DDDEF or DD; check RACF for the SMP/E userid.",
    example: "GIM42801E DDDEF SMPMTS COULD NOT BE ALLOCATED - DATA SET NOT FOUND" },
  { code: "GIM61901E", title: "INSTALL JOB FAILED", category: "SMP/E", severity: "ERROR",
    description: "Element installation step (link-edit, copy, etc.) failed inside APPLY.",
    cause: "Linker error (IEW...), copy error (IEB...), or other utility issue.",
    fix: "Review the failing utility's SYSPRINT; correct the underlying problem.",
    example: "GIM61901E LINK-EDIT FAILED FOR ELEMENT MYMOD WITH RC=12" },
  { code: "GIM37601E", title: "BYPASS INVALID", category: "SMP/E", severity: "ERROR",
    description: "BYPASS specified an unsupported keyword.",
    cause: "Misspelled BYPASS keyword or invalid in current SMP/E release.",
    fix: "Use BYPASS(HOLDSYSTEM,HOLDFIXCAT,HOLDUSER,HOLDCLASS,APARS,...).",
    example: "GIM37601E BYPASS(REQUIRES) IS NOT VALID" },
  { code: "GIM22701W", title: "OLDER LEVEL ALREADY INSTALLED", category: "SMP/E", severity: "WARNING",
    description: "A SYSMOD is being applied that supersedes one already in the zone.",
    cause: "Service stream — newer PTF subsumes older one.",
    fix: "Informational; let APPLY proceed.",
    example: "GIM22701W UO34567 SUPERSEDES UO11111 ALREADY IN ZONE" },
  { code: "GIM44102W", title: "RETURN CODE 4", category: "SMP/E", severity: "WARNING",
    description: "Generic warning return code indicating non-fatal issues.",
    cause: "Often: report shows missing fixes, or BYPASS used.",
    fix: "Review SMPRPT for details and plan follow-up.",
    example: "GIM44102W APPLY ENDED WITH RC=4 - WARNINGS PRESENT" },
  { code: "GIM39701E", title: "RETURN CODE 12", category: "SMP/E", severity: "ERROR",
    description: "SMP/E ended with return code 12 indicating a severe issue.",
    cause: "One or more APPLY/ACCEPT steps failed.",
    fix: "Search SMPOUT for the failing SYSMOD and underlying cause; fix and retry.",
    example: "GIM39701E SMP/E PROCESSING ENDED WITH RETURN CODE 12" }
];
