/* Languages, Compilers and Runtimes - COBOL, PL/I, HLASM, LE, binder */
window.MF_CODES = [
  { code: "IGYDS0017", title: "COBOL UNDEFINED NAME", category: "COBOL COMPILE", severity: "ERROR",
    description: "COBOL compiler found a reference to a name that wasn't defined.",
    cause: "Typo in data name, missing copy book, or referenced field in wrong scope.",
    fix: "Check spelling, ensure COPY books are in SYSLIB, verify section's PROGRAM-ID.",
    example: "IGYDS0017-S 'WS-CUST-AMT' WAS NOT DEFINED AS A DATA-NAME" },
  { code: "IGYPS2121", title: "COBOL TYPE MISMATCH", category: "COBOL COMPILE", severity: "ERROR",
    description: "Operands in a MOVE/COMPUTE/IF have incompatible types.",
    cause: "Moving alpha to numeric, comparing PIC X to PIC 9 without conversion.",
    fix: "Use FUNCTION NUMVAL, REDEFINE, or correct operand types.",
    example: "MOVE WS-NAME TO WS-AMOUNT.\n*> IGYPS2121-S OPERAND TYPES INCOMPATIBLE" },
  { code: "IGZ0013S", title: "COBOL RUNTIME — FILE STATUS", category: "COBOL RUNTIME", severity: "ERROR",
    description: "COBOL runtime detected a file operation error and could not continue.",
    cause: "READ on closed file, WRITE to input file, or other I/O sequence error.",
    fix: "Add FILE STATUS clause and check status after each I/O call; correct the sequence.",
    example: "IGZ0013S A file operation cannot be completed. File: PROD-CUST." },
  { code: "IGZ0035S", title: "COBOL CALL FAILED", category: "COBOL RUNTIME", severity: "ERROR",
    description: "CALL statement could not locate the target program.",
    cause: "Module not in load library, dynamic call with wrong literal, or LE search order issue.",
    fix: "Confirm load module in STEPLIB; use CALL with PROCEDURE-POINTER for dynamic; check LE _CEE_RUNOPTS.",
    example: "CALL 'MYPGM' USING WS-PARM.\nIGZ0035S Program 'MYPGM' could not be located." },
  { code: "CEE3204S", title: "LE PROTECTION EXCEPTION", category: "LE", severity: "ERROR",
    description: "Language Environment detected a S0C4 protection exception condition.",
    cause: "Pointer is null or invalid; array/index out of bounds; storage corruption.",
    fix: "Read CEEDUMP for failing PSW and offset; trace pointer initialization.",
    example: "CEE3204S The system detected a protection exception (System Completion Code=0C4)" },
  { code: "CEE3207S", title: "LE DATA EXCEPTION", category: "LE", severity: "ERROR",
    description: "LE detected an S0C7 data exception — non-numeric value in numeric operand.",
    cause: "Reading uninitialized field, spaces in COMP-3, or bad input data.",
    fix: "Same fix as S0C7 — initialize fields, use NUMERIC test on input.",
    example: "CEE3207S The system detected a data exception (System Completion Code=0C7)" },
  { code: "CEE3250C", title: "LE GENERAL ERROR", category: "LE", severity: "ERROR",
    description: "Generic LE message indicating an unhandled condition was raised.",
    cause: "Various — preceding CEE messages give the actual condition.",
    fix: "Read all messages before CEE3250C; they identify the real error.",
    example: "CEE3250C The system or user abend U4038 R=00000000 was issued." },
  { code: "CEE3501S", title: "LE MODULE NOT FOUND", category: "LE", severity: "ERROR",
    description: "LE could not load the requested module.",
    cause: "Module not in any library in the LE search order, or wrong name on CALL.",
    fix: "Add load library to STEPLIB or use _CEE_ENVFILE to direct search.",
    example: "CEE3501S Module XYZ123 was not found." },
  { code: "CEE3DMP", title: "LE DIAGNOSTIC DUMP TAKEN", category: "LE", severity: "INFO",
    description: "LE generated a CEEDUMP showing condition tokens, traceback, and storage.",
    cause: "An abnormal termination triggered TRAP(ON) and dump option.",
    fix: "Inspect CEEDUMP DD — read the condition token in the header.",
    example: "CEE3DMP CEEDUMP written to SYSPRINT" },
  { code: "ASMA017W", title: "HLASM UNDEFINED SYMBOL", category: "HLASM", severity: "WARNING",
    description: "Assembler found a reference to a symbol that doesn't resolve.",
    cause: "Missing COPY, EXTRN, or label that doesn't exist in the program.",
    fix: "Add an EXTRN, COPY the macro book, or correct the label.",
    example: "ASMA017W UNDEFINED SYMBOL ABC123" },
  { code: "ASMA044E", title: "HLASM INVALID SYNTAX", category: "HLASM", severity: "ERROR",
    description: "Assembler statement has invalid syntax for the given mnemonic.",
    cause: "Wrong operand count, invalid register, or addressing mode mismatch.",
    fix: "Refer to Principles of Operation for instruction format.",
    example: "L     R4,R5\nASMA044E UNDEFINED SYMBOL R5 (expecting D(B) address)" },
  { code: "IEW2456E", title: "BINDER UNRESOLVED EXTERNAL", category: "BINDER", severity: "ERROR",
    description: "Linkage editor / binder could not resolve an external reference.",
    cause: "Module references an unresolved CALL, missing LIB INCLUDE, or wrong RES library.",
    fix: "Add INCLUDE for missing module, or correct LIB statement.",
    example: "IEW2456E SYMBOL MYSUB UNRESOLVED. NO AUTOCALL (NCAL) WAS REQUESTED" },
  { code: "IEW2470W", title: "BINDER WARNING", category: "BINDER", severity: "WARNING",
    description: "Binder issued a non-fatal warning during link-edit.",
    cause: "Replacement of a CSECT, duplicate ESDs, or RMODE/AMODE mismatch.",
    fix: "Review BIND options and module attributes.",
    example: "IEW2470W CSECT MYPGM REPLACED IN INPUT MODULE" },
  { code: "PLI IBM0001", title: "PL/I PRECOMPILE ERROR", category: "PL/I COMPILE", severity: "ERROR",
    description: "Enterprise PL/I compiler diagnostic error.",
    cause: "PL/I syntax error or unresolved INCLUDE.",
    fix: "Check the listed line; correct PL/I syntax.",
    example: "IBM0001I E SEMICOLON EXPECTED LINE 23" },
  { code: "ABEND 4083", title: "LE TERMINATION", category: "LE ABEND", severity: "ERROR",
    description: "Common LE abend code wrapping unhandled conditions in COBOL programs.",
    cause: "Subordinate error like S0C7 wrapped by LE TRAP(ON), often with ABTERMENC settings.",
    fix: "Examine CEEDUMP for original condition; CEE messages preceding the abend.",
    example: "CEE3204S protection exception -> ABEND U4038 -> displayed as 4083 in some logs" }
];
