/* Networking and Communications - TCP/IP, VTAM, FTP, SMTP, sockets */
window.MF_CODES = [
  { code: "EZA1701", title: "UNKNOWN HOST", category: "FTP", severity: "ERROR",
    description: "FTP client could not resolve the destination hostname.",
    cause: "DNS resolver failure, incorrect hostname, or no /etc/resolv.conf entry.",
    fix: "Verify hostname, check DNS server availability, test with PING/HOSTNAME from TSO.",
    example: "FTP> open badhost.example.com\nEZA1701 Unknown host badhost.example.com" },
  { code: "EZA1735I", title: "FTP STD RETURN — TRANSFER FAILED", category: "FTP", severity: "ERROR",
    description: "Standard FTP client message that a transfer or session failed.",
    cause: "Various — login failure, file not found on server, permissions, network drop.",
    fix: "Check preceding messages for the actual failure reason from the server.",
    example: "EZA1735I FTP Return Code = 27000, Error Code = 00002\n*> means data set not found on remote" },
  { code: "EZA2899I", title: "DATA SET NOT FOUND", category: "FTP", severity: "ERROR",
    description: "FTP server rejected a transfer because the requested data set does not exist.",
    cause: "Wrong DSN, missing catalog entry, or HFS path incorrect.",
    fix: "Verify path/DSN on the server side. Check FTP.DATA for default qualifier rules.",
    example: "GET 'MY.NONEXIST' local.txt\nEZA2899I Unknown data set MY.NONEXIST" },
  { code: "EZZ4324I", title: "TCP/IP STARTING", category: "TCP/IP", severity: "INFO",
    description: "Communications Server reports that TCP/IP stack is initializing.",
    cause: "S TCPIP start command issued.",
    fix: "Informational. Wait for EZZ8061I 'INITIALIZATION COMPLETE'.",
    example: "EZZ4324I TCPIP : STACK NAME = TCPIP - VERSION 02.05.00" },
  { code: "EZZ4356I", title: "PORT IN USE", category: "TCP/IP", severity: "ERROR",
    description: "A TCP/IP application could not bind to a port because it is already in use.",
    cause: "Another application already listening on the port, or port reserved for a different job.",
    fix: "Check the PROFILE for PORT statements; find owning application with NETSTAT BYTE.",
    example: "EZZ4356I PORT 8080 IS NOT AVAILABLE FOR USERID USER1" },
  { code: "EZD1166E", title: "TCP/IP CONFIGURATION ERROR", category: "TCP/IP", severity: "ERROR",
    description: "Configuration file processing failed.",
    cause: "Syntax error in PROFILE.TCPIP, RESOLVER.SETUP, or other config dataset.",
    fix: "Re-read TCP/IP Customization Guide. Run VARY TCPIP,,SYNTAXCHECK on profile.",
    example: "EZD1166E SYNTAX ERROR IN PROFILE.TCPIP LINE 042" },
  { code: "IST259I", title: "VTAM RESOURCE NOT FOUND", category: "VTAM", severity: "ERROR",
    description: "VTAM cannot find a named resource (LU, APPL, line, etc.).",
    cause: "Resource not defined in VTAMLST, or major node not active.",
    fix: "Verify the major/minor node names; activate (V NET,ACT,ID=node) the major node.",
    example: "IST259I LU01 NOT FOUND" },
  { code: "IST380E", title: "VTAM ALLOCATION ERROR", category: "VTAM", severity: "ERROR",
    description: "VTAM could not allocate storage or a control block due to resource shortage.",
    cause: "VTAM internal storage shortage; large user community or memory leak.",
    fix: "Restart VTAM or grow CSA. Check D NET,STORUSE for usage.",
    example: "IST380E STORAGE LIMIT REACHED FOR VTAM" },
  { code: "IST663I", title: "VTAM SNA SENSE CODE", category: "VTAM", severity: "ERROR",
    description: "VTAM reports an SNA sense code from a failed session or RU.",
    cause: "Session activation failure, mode mismatch, or RU rejected by partner.",
    fix: "Decode sense via SNA Network Programming reference (e.g., 080F0001 = no LU available).",
    example: "IST663I ACTPU REQUEST FAILED, SENSE=080F0001" },
  { code: "EZB1052I", title: "SOCKET BIND FAILED", category: "SOCKETS", severity: "ERROR",
    description: "Application bind() to a socket failed.",
    cause: "Port in use, RACF blocked port, or invalid address.",
    fix: "Use a different port, request RACF SERVAUTH access, or check NETSTAT for owner.",
    example: "bind(): EZB1052I PORT 80 ALREADY IN USE BY OWNER1" },
  { code: "EDC8128I", title: "CONNECTION REFUSED", category: "SOCKETS", severity: "ERROR",
    description: "TCP connect() refused by the remote system.",
    cause: "No listener on the port, firewall blocking, or qmgr/server down.",
    fix: "Verify the server is up and listening on the expected port.",
    example: "connect to 10.1.1.1:9080 failed\n EDC8128I Connection refused" },
  { code: "EDC8129I", title: "CONNECTION RESET", category: "SOCKETS", severity: "ERROR",
    description: "TCP connection abruptly reset by peer.",
    cause: "Remote application crashed, firewall sent RST, or load balancer killed idle connection.",
    fix: "Add retry logic; verify firewalls/timeouts; check remote logs.",
    example: "recv(): EDC8129I Connection reset by peer" },
  { code: "EZZ9293I", title: "FTP SERVER CONFIG ERROR", category: "FTP", severity: "ERROR",
    description: "FTP server detected a configuration issue at startup.",
    cause: "Bad FTP.DATA statement, missing data set, or RACF profile issue.",
    fix: "Validate FTP.DATA; check FTP server SYSPRINT for full error context.",
    example: "EZZ9293I ANONYMOUS LEVEL DEFINITION INVALID" },
  { code: "EZA0500", title: "FTP COMMAND ERROR", category: "FTP", severity: "ERROR",
    description: "FTP client received a server reply indicating the command was rejected.",
    cause: "Permission denied, syntax error, or file does not exist on server.",
    fix: "Read the 3-digit reply code (e.g., 550 = file not found) and adjust the command.",
    example: "FTP> get /tmp/nope.txt\n550 /tmp/nope.txt: No such file or directory\nEZA0500 ftp: 550 reply code" },
  { code: "INADDR_ANY", title: "SNA SENSE 0801", category: "VTAM", severity: "ERROR",
    description: "SNA sense code 0801 0000 — invalid session parameters in BIND.",
    cause: "Mode entry mismatch, mode not in mode table, or session parameters not negotiable.",
    fix: "Check the MODEENT used by application against partner's APPC mode definitions.",
    example: "SNA BIND failure: sense=08010000 - mode TPF0001 not found in MODETAB" }
];
