/* Printing and Output Management - PSF, JES output, Infoprint, AFP */
window.MF_CODES = [
  { code: "APS810I", title: "PSF PRINTER ERROR", category: "PSF", severity: "ERROR",
    description: "PSF reports a printer device error.",
    cause: "Printer offline, out of paper, jam, or communication failure.",
    fix: "Check printer console; restart FSA after correcting at the printer.",
    example: "APS810I PRINTER PRT01 INTERVENTION REQUIRED - PAPER JAM" },
  { code: "APS599I", title: "PSF RESOURCE NOT FOUND", category: "PSF", severity: "ERROR",
    description: "PSF could not find a print resource (font, page def, form def, overlay).",
    cause: "Resource library missing from FONTLIB/PSEGLIB/etc., or resource name wrong.",
    fix: "Check FONT/PSEG/OVERLAY DD concatenations; verify resource exists.",
    example: "APS599I PAGE DEFINITION P1A06462 NOT FOUND IN LIBRARY" },
  { code: "APS101I", title: "PSF STARTED", category: "PSF", severity: "INFO",
    description: "PSF FSA (Functional Subsystem Application) initialization complete.",
    cause: "S PSF or START PSFFSS issued.",
    fix: "Informational. Wait for FSA ACTIVE.",
    example: "APS101I PSF FSA PRT01 ACTIVE" },
  { code: "APS003I", title: "PSF DATASET ERROR", category: "PSF", severity: "ERROR",
    description: "PSF could not read or interpret a SYSOUT data set for printing.",
    cause: "Corrupted AFP data stream, mismatched FORMDEF/PAGEDEF, or invalid AFPDS records.",
    fix: "Validate output via AFP viewer; review FORMDEF/PAGEDEF for compatibility.",
    example: "APS003I DATA SET ERROR - INVALID AFPDS STRUCTURED FIELD AT OFFSET 0512" },
  { code: "AOP1234E", title: "INFOPRINT SERVER ERROR", category: "INFOPRINT", severity: "ERROR",
    description: "Infoprint Server detected a configuration or processing error.",
    cause: "Bad printer definition, missing transform, or invalid SAPI parameter.",
    fix: "Check aopd.conf / aopxfd.conf and printer attributes via pdls.",
    example: "AOP1234E Transform PCL-to-AFP failed for job J00001" },
  { code: "AOP020I", title: "INFOPRINT JOB FAILED", category: "INFOPRINT", severity: "ERROR",
    description: "Infoprint Server could not deliver the job.",
    cause: "Destination printer offline, network down, or printer rejected the job.",
    fix: "Check destination state via pdq; ensure connectivity.",
    example: "AOP020I JOB J00001 FAILED - PRINTER PRT01 NOT-RESPONDING" },
  { code: "AOPnnnnW", title: "INFOPRINT WARNING", category: "INFOPRINT", severity: "WARNING",
    description: "Generic Infoprint Server warning — operation completed but with conditions.",
    cause: "Resource substitution, font fallback, or non-critical issue.",
    fix: "Review warning context; usually informational.",
    example: "AOP6789W Substituted font: Courier for missing GT12345" },
  { code: "PSF U0100", title: "PSF ABEND", category: "PSF ABEND", severity: "ERROR",
    description: "PSF user abend during printer processing.",
    cause: "PSF detected an unrecoverable condition (resource fault, FSI break).",
    fix: "Check PSF SYSLOG; restart FSA; if recurring, contact IBM.",
    example: "PSF FSA PRT01 ABEND U0100 - FSI INTERFACE FAILURE" },
  { code: "IP PrintWay ANFM", title: "PRINTWAY TRANSMISSION ERROR", category: "IP PrintWay", severity: "ERROR",
    description: "IP PrintWay could not transmit a job to a network printer.",
    cause: "TCP/IP connection refused, LPR error, or IPP error.",
    fix: "Verify printer IP, check NETSTAT for TCP/IP state; review IP PrintWay log.",
    example: "ANFM0123E Transmission failed - target 10.1.1.50:9100 connection refused" },
  { code: "JESPOOL EXCEEDED", title: "SYSOUT SPOOL LIMIT", category: "JES OUTPUT", severity: "ERROR",
    description: "Job's SYSOUT output exceeded the OUTLIM limit.",
    cause: "Print loop, debug DISPLAY in production loop, or unexpectedly large output.",
    fix: "Trim output; raise OUTLIM if legitimately needed.",
    example: "$HASP060 JOB EXCEEDED OUTLIM 50000 LINES" },
  { code: "PSF FONT WARN", title: "FONT NOT AVAILABLE", category: "PSF", severity: "WARNING",
    description: "Requested font was not found; PSF substituted a similar font.",
    cause: "Font CSECT not in FONTLIB, or wrong font set on FORMDEF.",
    fix: "Add the font to FONTLIB or update FORMDEF to use available fonts.",
    example: "PSF: FONT X0GT15 NOT FOUND - SUBSTITUTED WITH X0GT12" },
  { code: "AFP DATA STREAM", title: "AFP STRUCTURED FIELD ERROR", category: "AFP", severity: "ERROR",
    description: "Invalid structured field in AFPDS stream.",
    cause: "Application generated malformed AFP, or corrupted SYSOUT.",
    fix: "Inspect the AFPDS with AFP Workbench; correct the application's emission.",
    example: "INVALID SF X'D3A8AF' AT OFFSET 02048 - LENGTH MISMATCH" },
  { code: "IEC080I", title: "SYSOUT CLOSE ERROR", category: "JES OUTPUT", severity: "ERROR",
    description: "SYSOUT data set could not be closed properly.",
    cause: "Spool space shortage during CLOSE, or JES2 problem.",
    fix: "Resolve spool shortage; check JES2 commands.",
    example: "IEC080I JOBNAME,STEPNAME,SYSPRINT CLOSE FAILED RC=08" },
  { code: "APS010I", title: "PSF JOB COMPLETE", category: "PSF", severity: "INFO",
    description: "PSF finished printing a job successfully.",
    cause: "Normal end-of-job processing.",
    fix: "Informational.",
    example: "APS010I JOB J00001 PRINTED ON PRT01 - 250 PAGES" },
  { code: "APSGEN001", title: "PSF GENERATOR ERROR", category: "PSF", severity: "ERROR",
    description: "PSF resource generator detected an error processing a resource.",
    cause: "Page seg/form def/etc. has invalid structured fields.",
    fix: "Recreate the resource using current AFP tools; check version compatibility.",
    example: "APSGEN001 INVALID PAGE SEGMENT P1IMAGE1 - SF SEQUENCE INVALID" }
];
