/* Scheduling, Monitoring and Automation - TWS, Control-M, NetView, OMEGAMON */
window.MF_CODES = [
  { code: "EQQE001E", title: "TWS GENERAL ERROR", category: "TWS", severity: "ERROR",
    description: "IBM Workload Scheduler (TWSz / OPC) reported a controller error.",
    cause: "Controller could not communicate with a tracker, or internal data set corruption.",
    fix: "Check EQQMLOG for the specific reason; verify trackers via D NETSTAT and EQQOPER MSGLOG.",
    example: "EQQE001E TRACKER ON CPU01 NOT RESPONDING" },
  { code: "EQQF002I", title: "JOB SUBMITTED", category: "TWS", severity: "INFO",
    description: "TWS controller submitted a job to a tracker.",
    cause: "Plan-driven submission event.",
    fix: "Informational. Track in MCP or job history if needed.",
    example: "EQQF002I JOB ABC.JOB001 SUBMITTED TO TRACKER CPU01" },
  { code: "EQQE037E", title: "JOB ENDED IN ERROR", category: "TWS", severity: "ERROR",
    description: "TWS detected an operation ended with an error highest condition code.",
    cause: "Submitted job abended or returned code above ERROR threshold.",
    fix: "Open the operation in MCP; review the JESYSMSG and job log for actual abend.",
    example: "EQQE037E OPERATION CPU01/MYJOB ENDED IN ERROR WITH CODE S0C7" },
  { code: "EQQW001E", title: "WORKSTATION ERROR", category: "TWS", severity: "ERROR",
    description: "A workstation (CPU, server) is unavailable or in error state.",
    cause: "Tracker stopped, NJE connection lost, or hardware issue.",
    fix: "Restart the tracker (S EQQTRK); check VTAM/NJE connection.",
    example: "EQQW001E WORKSTATION CPU02 IS NOT AVAILABLE" },
  { code: "AOFA001E", title: "AUTOMATION COMMAND FAILED", category: "SA", severity: "ERROR",
    description: "System Automation could not execute a command.",
    cause: "Wrong command syntax, resource not in active state, or NetView session down.",
    fix: "Check INGAUTO log; verify the automation table entries.",
    example: "AOFA001E COMMAND 'STOP CICSA' FAILED - RESOURCE NOT ACTIVE" },
  { code: "AOF036E", title: "AUTOMATION TABLE ERROR", category: "SA", severity: "ERROR",
    description: "Automation table entry referenced an undefined command or condition.",
    cause: "Typo in automation table, missing exit command, or invalid condition.",
    fix: "Reload automation table after correcting; check INGSEND log.",
    example: "AOF036E AUTOMATION FOR MSG IEF450I FAILED — CMD MYCMD NOT DEFINED" },
  { code: "INGY001E", title: "AUTOMATION POLICY ERROR", category: "SA", severity: "ERROR",
    description: "System Automation policy build or activation failed.",
    cause: "Policy syntax errors, missing references between domains.",
    fix: "Use INGPOL to build; check for syntax errors and resolve broken references.",
    example: "INGY001E POLICY BUILD FAILED - APG NOT FOUND IN DOMAIN PROD" },
  { code: "CNM01001I", title: "NETVIEW INITIALIZATION", category: "NETVIEW", severity: "INFO",
    description: "NetView is starting up.",
    cause: "Normal startup message.",
    fix: "Informational. Wait for ready state.",
    example: "CNM01001I NETVIEW INITIALIZATION IN PROGRESS" },
  { code: "DSI002I", title: "NETVIEW COMMAND ERROR", category: "NETVIEW", severity: "ERROR",
    description: "NetView could not process a command.",
    cause: "Misspelled command, missing CLIST, or unauthorized command.",
    fix: "Verify command syntax and operator authorization.",
    example: "DSI002I COMMAND XYZ NOT VALID" },
  { code: "DSI047E", title: "NETVIEW SESSION ERROR", category: "NETVIEW", severity: "ERROR",
    description: "Session to a managed resource failed.",
    cause: "Resource inactive, VTAM session not bound, or LU not defined.",
    fix: "V NET,ACT to activate resources; verify VTAM definitions.",
    example: "DSI047E SESSION TO LU01 LOST - SENSE=08010000" },
  { code: "Control-M U016", title: "JOB ENDED NOT OK", category: "CONTROL-M", severity: "ERROR",
    description: "Control-M flagged a job as ended-not-ok based on completion code rules.",
    cause: "Job condition code exceeded MAXRC, or required output file not produced.",
    fix: "Review the job's actual return code; rerun after correction or override.",
    example: "Control-M PROD.NIGHTLY.MYJOB - STATE: ENDED NOT OK (CC=8)" },
  { code: "OMEGAMON KO2I001", title: "OMEGAMON STARTUP", category: "OMEGAMON", severity: "INFO",
    description: "OMEGAMON product started successfully.",
    cause: "Normal startup of a Tivoli Monitoring (ITM) server or agent.",
    fix: "Informational; verify the started task is up and TEMS connection works.",
    example: "KO2I001I OMEGAMON FOR Z/OS STARTED" },
  { code: "OMEGAMON KO2W014", title: "EXCEPTION TRIGGERED", category: "OMEGAMON", severity: "WARNING",
    description: "An OMEGAMON exception threshold was crossed.",
    cause: "Workload, paging, or response time exceeded the configured exception level.",
    fix: "Investigate the workload showing the exception; tune or relieve the resource.",
    example: "KO2W014W EXCEPTION: AUX UTIL > 80% (current 87%)" },
  { code: "BMC MainView WARN", title: "MAINVIEW ALERT", category: "MAINVIEW", severity: "WARNING",
    description: "BMC MainView raised an alert from a monitored target.",
    cause: "Resource threshold crossed (CPU, response time, queue depth, etc.).",
    fix: "Drill into the alert in MainView for details; address the underlying cause.",
    example: "MainView ALERT: CICS REGION CICSA RESPONSE TIME > 2 SEC" },
  { code: "EQQ0001I", title: "TWS MESSAGE LOG START", category: "TWS", severity: "INFO",
    description: "EQQMLOG / job log start banner for TWS.",
    cause: "Normal output banner.",
    fix: "Informational. Used to anchor log analysis.",
    example: "EQQ0001I LOG STARTED AT 2026-06-14 08:00:00 - CONTROLLER TWSC1" }
];
