/* Security and Cryptography - RACF, ACF2, Top Secret, ICSF, SSL */
window.MF_CODES = [
  { code: "ICH408I", title: "INSUFFICIENT ACCESS AUTHORITY", category: "RACF", severity: "ERROR",
    description: "RACF denied access to a protected resource. Shows the resource, intended access, and actual access granted.",
    cause: "User lacks the required level of access (READ, UPDATE, ALTER, EXECUTE) on the profile.",
    fix: "Request PERMIT from security admin, or use generic profile that includes the user.",
    example: "ICH408I USER(USER1)  GROUP(GRP01) NAME(...)\n  PROD.PAYROLL CL(DATASET)\n  INSUFFICIENT ACCESS AUTHORITY\n  FROM PROD.PAYROLL (G)\n  ACCESS INTENT(UPDATE)  ACCESS ALLOWED(READ)" },
  { code: "ICH415I", title: "PASSWORD INVALID", category: "RACF", severity: "ERROR",
    description: "Logon attempt rejected due to invalid password.",
    cause: "Wrong password entered, expired password, or revoked user.",
    fix: "User resets password (LU command, or PASSWORD on TSO). Admin can also reset.",
    example: "ICH415I PASSWORD INCORRECT" },
  { code: "ICH70001I", title: "LAST ACCESS / LOGON SUCCESSFUL", category: "RACF", severity: "INFO",
    description: "User logged on successfully — RACF reports the last access time.",
    cause: "Normal successful logon.",
    fix: "Informational. Verify last access is when user expected.",
    example: "ICH70001I USER1 LAST ACCESS AT 09:45:12 ON FRIDAY, JUNE 14, 2026" },
  { code: "ICH04001I", title: "RACF COMMAND ERROR", category: "RACF", severity: "ERROR",
    description: "RACF command (ADDUSER, ALTUSER, PERMIT, etc.) failed.",
    cause: "Invalid syntax, profile not found, or insufficient authority to execute the command.",
    fix: "Read the message text and the following IRR... message for specifics.",
    example: "ICH04001I COMMAND PROCESSING ENDED WITH AN ERROR\n  IRR52007I YOU ARE NOT AUTHORIZED TO ADD USERS" },
  { code: "ICH13003I", title: "CERTIFICATE NOT VALID", category: "RACF DIGTCERT", severity: "ERROR",
    description: "A digital certificate operation failed because the certificate is invalid or expired.",
    cause: "Expired certificate, missing CA certificate in keyring, or signature mismatch.",
    fix: "RACDCERT LIST to check expiration; renew or reissue the certificate.",
    example: "ICH13003I CERTIFICATE EXPIRED ON 2025-12-31" },
  { code: "CSFM001E", title: "ICSF INITIALIZATION ERROR", category: "ICSF", severity: "ERROR",
    description: "ICSF could not initialize cryptographic services.",
    cause: "Missing CKDS/PKDS/TKDS data sets, CCA card offline, or RACF blocked ICSF startup.",
    fix: "Verify CKDS/PKDS allocation; check CRYPTO card status (D ICSF,CARD).",
    example: "CSFM001E ICSF INITIALIZATION FAILED - CKDS NOT FOUND" },
  { code: "CSFM015E", title: "ICSF SERVICE FAILURE", category: "ICSF", severity: "ERROR",
    description: "A cryptographic API call (encrypt, decrypt, sign) failed.",
    cause: "Key not found, wrong key label, or hardware crypto problem.",
    fix: "Verify key exists with KGUP/csfclr commands; check return/reason in caller.",
    example: "CSFM015E SERVICE CSNBSAE FAILED - KEY LABEL TEST.AES NOT FOUND" },
  { code: "GSK00112W", title: "GSKKYMAN CERT WARNING", category: "GSKit", severity: "WARNING",
    description: "Certificate management warning — typically certificate near expiration.",
    cause: "GSKKYMAN found a certificate within its expiration warning period.",
    fix: "Renew the certificate; update key database with new cert.",
    example: "GSK00112W Certificate 'mywebcert' expires on 2026-09-01 - 60 days" },
  { code: "GSK01036E", title: "SSL HANDSHAKE FAILED", category: "GSKit", severity: "ERROR",
    description: "SSL/TLS handshake between client and server failed.",
    cause: "Cipher mismatch, expired cert, missing CA cert, or TLS version mismatch.",
    fix: "Check TLS levels; verify certificate chain; enable trace via GSK_TRACE for diagnosis.",
    example: "GSK01036E SSL handshake failed - no matching cipher suite" },
  { code: "ACFAE001", title: "ACF2 ACCESS DENIED", category: "ACF2", severity: "ERROR",
    description: "ACF2 logging-mode or abort-mode rejected access to a resource.",
    cause: "Missing rule entry permitting the user, or rule rejected the access.",
    fix: "Have ACF2 admin compile a rule entry permitting the access.",
    example: "ACF99908 USER1 DSN(PROD.MASTER) ACCESS DENIED BY ACF2 RULE" },
  { code: "TSS7000", title: "TOP SECRET ACCESS DENIED", category: "TOP SECRET", severity: "ERROR",
    description: "CA Top Secret rejected access to a protected resource.",
    cause: "User does not own/permit the data set, profile not in acid.",
    fix: "TSS PERMIT acid(USER1) DSN(PROD.MASTER) ACCESS(READ).",
    example: "TSS7000E DATASET PROD.MASTER NOT IN OWNED LIST OF USER1" },
  { code: "S047", title: "UNAUTHORIZED PROGRAM", category: "SECURITY ABEND", severity: "ERROR",
    description: "A program tried to execute an APF-restricted instruction or service from non-APF library.",
    cause: "Module not APF authorized but tried to execute privileged SVC or MODESET.",
    fix: "Add the load library to APF list (PROGxx or SETPROG APF,ADD) and link with AC=1.",
    example: "Program issued MODESET KEY=ZERO from non-APF load module -> S047" },
  { code: "ABEND 913", title: "RACF DATA SET ACCESS DENIED", category: "SECURITY ABEND", severity: "ERROR",
    description: "RACF rejected data set access at OPEN time, causing abend S913.",
    cause: "User has no profile entry, or access intent exceeds permitted level.",
    fix: "RACF PERMIT for the user, or move data set into a generic profile that includes them.",
    example: "OPEN failed with S913 - ICH408I showed READ requested, NONE allowed" },
  { code: "IRRRCK001", title: "PASSWORD PHRASE INVALID", category: "RACF", severity: "ERROR",
    description: "Password phrase change rejected — does not meet SETROPTS PASSPHRASE rules.",
    cause: "Phrase too short, doesn't include required character classes, or matches history.",
    fix: "Use a longer phrase with mixed character classes per SETROPTS PASSPHRASE rules.",
    example: "PHRASE CHANGE: Phrase must be at least 14 characters and include digits" }
];
