/* Storage and Data Sets - VSAM, IDCAMS, DFSMS, catalog, file I/O */
window.MF_CODES = [
  { code: "IDC3009I", title: "VSAM CATALOG RETURN CODE", category: "IDCAMS", severity: "ERROR",
    description: "IDCAMS reports a non-zero return code from the catalog service. The reason code identifies the problem.",
    cause: "VSAM catalog access failed — examples: data set not found (RC=8,reason=42), already exists (RC=8,reason=38), security failure (reason=4).",
    fix: "Decode the reason code via Catalog Diagnosis. Common: 42 = data set not in catalog, 38 = duplicate, 84 = no space.",
    example: "IDC3009I ** VSAM CATALOG RETURN CODE IS 8 - REASON CODE IS IGG0CLEH-42" },
  { code: "IDC0001I", title: "FUNCTION COMPLETED WITH MAXIMUM CONDITION CODE", category: "IDCAMS", severity: "INFO",
    description: "IDCAMS reports the maximum condition code from the executed commands.",
    cause: "Issued at end of each command and at job end.",
    fix: "Investigate any non-zero condition codes shown.",
    example: "IDC0001I FUNCTION COMPLETED, HIGHEST CONDITION CODE WAS 0" },
  { code: "IDC3308I", title: "DUPLICATE RECORD", category: "IDCAMS", severity: "ERROR",
    description: "REPRO encountered a record with a key that already exists in the output KSDS.",
    cause: "Loading a KSDS with duplicate keys, or replicating without REPLACE.",
    fix: "Sort and dedupe the input, or specify REPLACE on the REPRO.",
    example: "REPRO INFILE(IN) OUTFILE(OUT)\nIDC3308I ** DUPLICATE RECORD" },
  { code: "IDC3014I", title: "VSAM I/O RETURN CODE", category: "VSAM", severity: "ERROR",
    description: "Generic VSAM I/O failure reported by IDCAMS. The return code identifies the specific problem.",
    cause: "Various VSAM I/O failures — physical error, structural problem, no record found.",
    fix: "Decode return/reason codes via VSAM macro return codes table. Run EXAMINE on the cluster.",
    example: "IDC3014I VSAM I/O RETURN CODE IS 116 - RPLFDBWD = X'00000074'" },
  { code: "VSAM-4", title: "END OF FILE", category: "VSAM RC", severity: "INFO",
    description: "VSAM return code 4 — End of data reached on a sequential read.",
    cause: "Read past the last record in a KSDS/ESDS/RRDS.",
    fix: "Normal end-of-file condition; close the file and continue.",
    example: "READ MY-FILE.\nIF VSAM-FB-CODE = '04' AT-END...." },
  { code: "VSAM-8", title: "DUPLICATE KEY", category: "VSAM RC", severity: "ERROR",
    description: "VSAM return code 8 (file status 22) — attempted to insert a record with a duplicate key in a UNIQUE KSDS.",
    cause: "Application tried to WRITE a record whose key already exists.",
    fix: "Check for duplicate via READ before WRITE, or REWRITE if updating, or change to non-unique alternate index.",
    example: "WRITE CUST-REC.\nIF CUST-STATUS = '22' DISPLAY 'DUPLICATE KEY'." },
  { code: "VSAM-23", title: "RECORD NOT FOUND", category: "VSAM RC", severity: "ERROR",
    description: "File status 23 — READ did not find the requested record in the KSDS.",
    cause: "Key value not present, or alternate index out of sync with base cluster.",
    fix: "Validate the key, or rebuild the alternate index with BLDINDEX if it's stale.",
    example: "MOVE 'X999' TO CUST-KEY.\nREAD CUSTOMER INVALID KEY DISPLAY 'NOT FOUND'." },
  { code: "VSAM-92", title: "LOGIC ERROR", category: "VSAM RC", severity: "ERROR",
    description: "File status 92 — logic error such as opening already-open file or invalid sequence.",
    cause: "Trying to READ before OPEN, REWRITE without previous READ, or OPEN on already-open file.",
    fix: "Trace the application's I/O sequence; OPEN before READ; READ before REWRITE.",
    example: "OPEN INPUT FILE-A.\nOPEN INPUT FILE-A.   *> already open -> status 92" },
  { code: "IGD17040I", title: "DATA SET ALREADY EXISTS", category: "DFSMS", severity: "ERROR",
    description: "Allocation failed because a data set with the same name already exists in the catalog.",
    cause: "DISP=NEW on a DD whose DSN is already cataloged.",
    fix: "Use DISP=MOD or delete the existing data set first with IDCAMS DELETE.",
    example: "IGD17040I DATA SET PROD.MY.FILE ALREADY EXISTS IN CATALOG" },
  { code: "IGD17501I", title: "ATTEMPT TO ALLOCATE FAILED", category: "DFSMS", severity: "ERROR",
    description: "SMS allocation could not find an eligible volume for the data set.",
    cause: "Storage class points to a storage group whose volumes are all full or have insufficient free space.",
    fix: "Add volumes, free space, or pick a different storage class.",
    example: "IGD17501I FAILED TO SELECT A VOLUME FOR DATA SET MY.NEW.FILE" },
  { code: "EDC5061I", title: "OPEN ERROR ON VSAM FILE", category: "LE/VSAM", severity: "ERROR",
    description: "Language Environment OPEN failed for a VSAM data set under C or COBOL.",
    cause: "The cluster doesn't exist, RACF denies access, or the DD has incorrect parameters.",
    fix: "Verify cluster existence and access; check stdin/stdout/stderr routing in C.",
    example: "EDC5061I An error occurred when attempting to define a file to the system." },
  { code: "IEC031I", title: "INPUT DATA SET INCORRECTLY SPECIFIED", category: "I/O", severity: "ERROR",
    description: "DCB or DD attributes mismatch between the program's expectation and the data set's actual attributes.",
    cause: "RECFM, LRECL, or BLKSIZE differs from the data set's label.",
    fix: "Match the program's DCB to the data set, or override on the DD with DCB=(...) values.",
    example: "IEC031I D37-04,JOB,STEP,SYSPRINT,...,'X37'\n*> attempted to write more than primary, no secondary" },
  { code: "IEC031D37", title: "ABEND D37 — NO SECONDARY SPACE", category: "I/O", severity: "ERROR",
    description: "An output data set ran out of space and no secondary extent was specified.",
    cause: "DD allocated with only primary space and the data exceeded that.",
    fix: "Add secondary space: SPACE=(CYL,(10,2)). Increase primary if you can size it.",
    example: "//OUT DD DSN=BIG,SPACE=(CYL,(5))    *> no secondary -> D37" },
  { code: "IEC031E37", title: "ABEND E37 — MAX EXTENTS REACHED", category: "I/O", severity: "ERROR",
    description: "The data set hit the maximum allowable extents (16 per volume for non-extended).",
    cause: "Many small secondary extents allocated, all consumed; extended-format not used.",
    fix: "Reorg/Compress the data set, or define as extended-format to allow up to 123 extents.",
    example: "IEC031I E37-04 ... data set reached 16-extent limit" },
  { code: "IEC031B37", title: "ABEND B37 — VOLUME OUT OF SPACE", category: "I/O", severity: "ERROR",
    description: "The volume holding the data set has no more space and there's no candidate volume for extension.",
    cause: "Volume full; data set required additional extent but couldn't be satisfied.",
    fix: "Move data set to a volume with more free space, or REORG to recover space.",
    example: "IEC031I B37-04 ... volume PRD001 has no free space" }
];
