/* Interactive Tools and Scripting - TSO/E, ISPF, SDSF, REXX */
window.MF_CODES = [
  { code: "IKJ56644I", title: "TSO COMMAND NOT FOUND", category: "TSO/E", severity: "ERROR",
    description: "TSO command processor could not find the named command.",
    cause: "Misspelled command, missing CLIST/REXX library in SYSPROC, or unauthorized command.",
    fix: "Verify spelling; confirm CLIST/REXX is in SYSPROC concatenation or invoke with EXEC.",
    example: "READY\nWHEREIS MYDS\nIKJ56644I NO COMMAND PROCESSOR FOR THIS COMMAND" },
  { code: "IKJ56228I", title: "DATA SET NOT IN CATALOG", category: "TSO/E", severity: "ERROR",
    description: "Requested data set is not cataloged on this system.",
    cause: "Typo in DSN, data set not yet created, or uncataloged.",
    fix: "LISTC ENT(...) to confirm; use ALLOCATE if creating new.",
    example: "READY\nLISTDS 'MY.NONEXIST'\nIKJ56228I DATA SET 'MY.NONEXIST' NOT IN CATALOG OR CATALOG CAN NOT BE ACCESSED" },
  { code: "IKJ56250I", title: "DATA SET BEING USED", category: "TSO/E", severity: "ERROR",
    description: "Cannot acquire exclusive access — another job/user has the data set.",
    cause: "Concurrent batch job, ISPF edit session, or held by another TSO user.",
    fix: "Wait or find the holder via D GRS,RES=(*,dsn).",
    example: "ALLOCATE F(IN) DA('PROD.MASTER') SHR\nIKJ56250I DATA SET PROD.MASTER BEING USED BY ANOTHER USER" },
  { code: "IKJ56500I", title: "COMMAND NOT FOUND", category: "TSO/E", severity: "ERROR",
    description: "TSO/E could not find the command, CLIST, or REXX in any library.",
    cause: "Missing from SYSPROC, SYSEXEC, or load library.",
    fix: "Verify command name, check SYSPROC/SYSEXEC for the library containing it.",
    example: "READY\nMYREXX\nIKJ56500I COMMAND MYREXX NOT FOUND" },
  { code: "ISPS003", title: "ISPF SERVICE ERROR", category: "ISPF", severity: "ERROR",
    description: "ISPF dialog service (VGET, TBOPEN, etc.) returned an error.",
    cause: "Variable not defined, table not allocated, file not in ISPTABL, or syntax error.",
    fix: "Use ISPLNK trace or ISRDDN to inspect ISPF datasets; check return code in dialog.",
    example: "ISPS003 SEVERE ERROR (TBOPEN, RC=8) - TABLE MYTAB NOT FOUND" },
  { code: "ISPF1", title: "PANEL DEFINITION ERROR", category: "ISPF", severity: "ERROR",
    description: "ISPF could not parse a panel definition.",
    cause: "Invalid )ATTR, )BODY, )INIT, )PROC syntax in the panel.",
    fix: "Re-validate the panel via ISPSTRT TEST mode and examine the panel source.",
    example: "ISPF1 PANEL MYPANEL HAS A SYNTAX ERROR ON LINE 12" },
  { code: "ISPP013", title: "ISPF VAR NOT DEFINED", category: "ISPF", severity: "ERROR",
    description: "A panel referenced a variable that hasn't been defined in the dialog.",
    cause: "Missing VDEFINE, or variable hasn't been VPUT to shared/profile pool.",
    fix: "VDEFINE the variable before display, or initialize in )INIT section.",
    example: "ISPP013 VARIABLE NAME1 NOT DEFINED IN PROFILE POOL" },
  { code: "ISF021I", title: "SDSF AUTHORIZATION ERROR", category: "SDSF", severity: "ERROR",
    description: "User not authorized to perform the requested SDSF action.",
    cause: "Missing SAF class profile (SDSF or JESSPOOL) for the action.",
    fix: "Request RACF PERMIT for the SDSF.* or JESSPOOL.* profile.",
    example: "ISF021I USER NOT AUTHORIZED TO CANCEL JOB JOB12345" },
  { code: "ISF002E", title: "SDSF NOT AVAILABLE", category: "SDSF", severity: "ERROR",
    description: "SDSF cannot connect to JES or the operator services it requires.",
    cause: "JES2/JES3 not started, or SDSF SAF restrictions block initial connection.",
    fix: "Check JES status (D JES); verify SDSF parmlib (ISFPRMxx) and SAF profiles.",
    example: "ISF002E SDSF JES2 INTERFACE NOT AVAILABLE" },
  { code: "IRX0040I", title: "REXX SYNTAX ERROR", category: "REXX", severity: "ERROR",
    description: "REXX detected a SYNTAX condition while interpreting source code.",
    cause: "Missing END for DO, missing closing quote, or invalid keyword.",
    fix: "Read the line/column shown in the message; fix the syntax.",
    example: "DO i=1 to 10\n  say i\n*missing END*\nIRX0040I ERROR RUNNING MYREXX LINE 4 - UNEXPECTED END OF DATA" },
  { code: "IRX0250E", title: "REXX FUNCTION ERROR", category: "REXX", severity: "ERROR",
    description: "External REXX function call failed.",
    cause: "Function not found, wrong argument types, or function returned error.",
    fix: "Check function library load order, argument types, and the function's documented return values.",
    example: "x = OUTTRAP('off',9999,'noconcat')\nIRX0250E FUNCTION OUTTRAP NOT FOUND" },
  { code: "REXX RC -3", title: "REXX SUBCOMMAND FAILURE", category: "REXX", severity: "ERROR",
    description: "Host command environment failed to find or process a subcommand.",
    cause: "ADDRESS environment doesn't support the command, or command misspelled.",
    fix: "Verify ADDRESS environment (TSO, ISPEXEC, SYSCALL, ISREDIT, etc.).",
    example: "ADDRESS TSO\n  'BADCOMMAND'\n  /* RC = -3 */" },
  { code: "REXX NOVALUE", title: "UNINITIALIZED VARIABLE", category: "REXX", severity: "WARNING",
    description: "REXX referenced a variable that hasn't been assigned a value.",
    cause: "Variable used before assignment, with SIGNAL ON NOVALUE active.",
    fix: "Initialize variables explicitly, or use VAR() / SYMBOL() before reading.",
    example: "say mydata    /* mydata never set */\n*> NOVALUE condition raised" },
  { code: "OMVS BPXFXxxx", title: "OMVS SHELL ERROR", category: "OMVS", severity: "ERROR",
    description: "UNIX System Services (OMVS) reported a service or shell error.",
    cause: "Permission denied, file system full, or signal interrupted command.",
    fix: "Use 'bpxmtext nnn' to decode the reason code; check ls -la and df -k.",
    example: "/bin/sh: mkdir: Permission denied\nBPXFAMSG 156: EACCES" },
  { code: "ISPC001", title: "ISPF INIT ERROR", category: "ISPF", severity: "ERROR",
    description: "ISPF initialization failed at startup.",
    cause: "Missing ISPF datasets (ISPMLIB, ISPPLIB, ISPSLIB, ISPTLIB) or corrupt profile.",
    fix: "Verify ISPF DD concatenations. Try ISPSTART with default profile.",
    example: "ISPC001 INITIALIZATION FAILED - ISPPROF DATA SET INVALID" }
];
