/* Transaction Processing and Messaging - CICS abends, DFH messages, MQ codes */
window.MF_CODES = [
  { code: "ASRA", title: "PROGRAM CHECK IN APPLICATION", category: "CICS ABEND", severity: "ERROR",
    description: "CICS detected a program check (S0Cx-style) in an application program.",
    cause: "S0C7 data exception, S0C4 protection, or other program-check condition raised during EXEC CICS RETURN.",
    fix: "Read the CICS transaction dump for the actual program-check type (often S0C7) and trace it like a batch S0C7.",
    example: "DFHAC2206 TRANSACTION TRAN ABEND ASRA AT 10:32:00\n  PROGRAM=MYPGM  OFFSET=X'1234'" },
  { code: "AICA", title: "RUNAWAY TASK", category: "CICS ABEND", severity: "ERROR",
    description: "A transaction exceeded the runaway task time limit and CICS terminated it.",
    cause: "Tight loop in application code or large processing with no CICS service to break the loop.",
    fix: "Locate the loop; add periodic EXEC CICS SUSPEND or other service to give CICS a dispatch point. Tune RUNAWAY value.",
    example: "DFHAC2206 TRAN APIN ABEND AICA — runaway 5000 ms exceeded" },
  { code: "AEY9", title: "INVALID PROGRAM CALL", category: "CICS ABEND", severity: "ERROR",
    description: "EXEC CICS LINK or XCTL failed because the target program is unavailable or disabled.",
    cause: "Target PROGRAM disabled in CICS, not in CSD, or not in the program load library.",
    fix: "CEDA INSTALL the program definition, enable it (CEMT SET PROGRAM(...) ENABLED), or fix the load library concatenation.",
    example: "EXEC CICS LINK PROGRAM('PGMB')\nDFHAC2206 ... ABEND AEY9 — program disabled" },
  { code: "AKCS", title: "TRANSACTION TIMEOUT (DTIMOUT)", category: "CICS ABEND", severity: "ERROR",
    description: "Transaction exceeded the DTIMOUT period without responding to terminal input.",
    cause: "Long-running task waiting on terminal input or external resource.",
    fix: "Tune DTIMOUT or restructure the task to be event-driven.",
    example: "DFHAC2206 TRAN ABEND AKCS — DTIMOUT 30 seconds exceeded" },
  { code: "APCT", title: "PROGRAM NOT FOUND", category: "CICS ABEND", severity: "ERROR",
    description: "The transaction's initial program could not be loaded.",
    cause: "PROGRAM definition missing in CSD, or PROGRAM not in DFHRPL load library.",
    fix: "CEDA DEFINE PROGRAM(...) GROUP(...) and CEMT NEWCOPY. Verify DFHRPL concatenation in the CICS region JCL.",
    example: "Transaction MYTR mapped to PGMA, but PGMA not in DFHRPL -> APCT." },
  { code: "AEIV", title: "VSAM FILE NOT OPEN", category: "CICS ABEND", severity: "ERROR",
    description: "EXEC CICS READ/WRITE referenced a file that wasn't open or definitions disagree.",
    cause: "FILE not OPEN, file disabled, or RACF blocked access.",
    fix: "CEMT INQ FILE(...) and SET FILE(...) OPEN. Check FCT/CSD and access auths.",
    example: "EXEC CICS READ FILE('CUST') INTO(...)  *> CUST closed -> AEIV" },
  { code: "DFHAC2003", title: "TERMINAL ABEND", category: "CICS", severity: "ERROR",
    description: "A terminal-related transaction abended because of terminal session issue.",
    cause: "Terminal disconnected, VTAM session loss, or LU not bound.",
    fix: "Verify VTAM status (V NET,DISPLAY,SCOPE=ALL). Reconnect terminal.",
    example: "DFHAC2003 TRAN MYTR ABEND ATCH AT 14:02 — TERMID=T001" },
  { code: "DFHFC0700", title: "FILE OPEN ERROR", category: "CICS", severity: "ERROR",
    description: "CICS could not open a file at startup or via CEMT.",
    cause: "Underlying VSAM cluster missing, RACF denied access, or attribute mismatch.",
    fix: "Verify cluster exists with LISTC; check RACF profile for CICS region userid.",
    example: "DFHFC0700 FILE CUST UNABLE TO OPEN. VSAM rc=8 reason=42" },
  { code: "MQRC 2033", title: "NO MESSAGE AVAILABLE", category: "MQ", severity: "INFO",
    description: "MQGET with no-wait found no messages on the queue.",
    cause: "Normal condition when polling an empty queue with MQGMO_NO_WAIT.",
    fix: "If polling, this is expected. Use MQGMO_WAIT for blocking get.",
    example: "MQGET HCONN, HOBJ, &MD, &GMO, ...\n  CompCode=2 (WARNING), Reason=2033" },
  { code: "MQRC 2009", title: "CONNECTION BROKEN", category: "MQ", severity: "ERROR",
    description: "The connection to the queue manager was lost.",
    cause: "Queue manager stopped, network failure, or channel disconnected.",
    fix: "Reconnect via MQCONN. Check qmgr status with DISPLAY QMSTATUS. Review error logs for FDC files.",
    example: "MQCMIT HCONN, ...\n  CompCode=2 Reason=2009 (MQRC_CONNECTION_BROKEN)" },
  { code: "MQRC 2059", title: "QUEUE MANAGER NOT AVAILABLE", category: "MQ", severity: "ERROR",
    description: "MQCONN failed because the queue manager is not running or not reachable.",
    cause: "Queue manager not started, wrong qmgr name, or client channel definition wrong.",
    fix: "Start the queue manager (strmqm), verify name, or fix MQSERVER environment / CCDT.",
    example: "MQCONN HCONN, 'QM01', ...\n  Reason=2059 - qmgr stopped" },
  { code: "CSQX004E", title: "CHANNEL ERROR", category: "MQ", severity: "ERROR",
    description: "MQ channel encountered an error and was disconnected.",
    cause: "Network problem, authentication failure, or channel definition mismatch between sides.",
    fix: "Check CHANNEL display, verify SSL certificates if applicable, and review the partner's logs.",
    example: "CSQX004E CHL=SVRCONN_CHL CONN failed. CompCode=2 Reason=2059" },
  { code: "CSQM050E", title: "QUEUE ERROR", category: "MQ", severity: "ERROR",
    description: "Queue manager could not access a queue (definition error or RACF block).",
    cause: "Queue does not exist, RACF block, or queue is GET-disabled/PUT-disabled.",
    fix: "DISPLAY QLOCAL/QREMOTE/QALIAS for the queue; verify RACF MQ class profile.",
    example: "CSQM050E QM01 ALTER QLOCAL('Q1') failed - not authorized" },
  { code: "DFHWB0123", title: "CICS WEB ERROR", category: "CICS WEB", severity: "ERROR",
    description: "CICS Web Services / HTTP request processing failed.",
    cause: "Pipeline configuration error, URIMAP not found, or remote endpoint failure.",
    fix: "Check URIMAP and PIPELINE definitions; review CICS web interface trace.",
    example: "DFHWB0123 HTTP request rejected - URIMAP not found for /api/orders" },
  { code: "DFHFC4701", title: "DEADLOCK ON FILE", category: "CICS", severity: "ERROR",
    description: "CICS task was rolled back due to a deadlock on a VSAM file or DB2 connection.",
    cause: "Two transactions held conflicting locks on the same record.",
    fix: "Restart the transaction; tune the application to acquire locks in consistent order.",
    example: "DFHFC4701 Transaction MYTR rolled back - deadlock on file CUST" }
];
