/* Vendor, Business and Custom Applications - User abends, ERP, banking */
window.MF_CODES = [
  { code: "U0001", title: "CUSTOM USER ABEND 1", category: "USER ABEND", severity: "ERROR",
    description: "Application-issued ABEND with completion code 1. Meaning depends on the application.",
    cause: "Custom code path raised a fatal error: validation failure, business rule violation, or sanity check.",
    fix: "Locate ABEND or CEE3AB2 call in source code; meaning is application-specific.",
    example: "IF WS-BAD-DATA = 'Y'\n   MOVE 1 TO WS-ABEND-CODE\n   CALL 'CEE3AB2' USING WS-ABEND-CODE BY VALUE 0 RETURNING RC" },
  { code: "U0016", title: "CUSTOM USER ABEND 16", category: "USER ABEND", severity: "ERROR",
    description: "Generic 'fatal error' user abend code widely used as a catch-all.",
    cause: "Application chose code 16 as its fatal abend value. Often issued when no specific recovery is possible.",
    fix: "Look at the messages issued before the abend; they identify the actual failure.",
    example: "JOB FAILED ABEND U0016 — preceded by application's WS-MSG: 'INVALID INPUT FILE FORMAT'" },
  { code: "U1024", title: "VALIDATION FAILURE", category: "USER ABEND", severity: "ERROR",
    description: "Common convention for an input-validation user abend.",
    cause: "Field failed business rule (range, type, codeset).",
    fix: "Inspect the input record number/key reported by the application's error log.",
    example: "Application abend U1024 with message: 'ACCOUNT FORMAT INVALID - REC 12345'" },
  { code: "U2000", title: "BATCH PROCESSING ABEND", category: "USER ABEND", severity: "ERROR",
    description: "Convention used by batch frameworks for unrecoverable processing failures.",
    cause: "Framework detected unrecoverable state; commonly database update failure.",
    fix: "Review framework log files; check restart procedures.",
    example: "Job abend U2000 - framework log shows DB2 -911 deadlock not retryable" },
  { code: "U3000", title: "INTEGRATION ABEND", category: "USER ABEND", severity: "ERROR",
    description: "Convention used by interface programs for upstream/downstream errors.",
    cause: "External system unreachable, contract violation in payload, or timeout.",
    fix: "Check connectivity to external system; verify message format.",
    example: "INT-ERROR: SAP NOT RESPONDING -> ABEND U3000" },
  { code: "U4093", title: "LE ABEND CONVERSION", category: "USER ABEND", severity: "ERROR",
    description: "Alternative LE abend wrap commonly seen in COBOL with TERMTHDACT settings.",
    cause: "LE converted an underlying condition to a user abend per runtime options.",
    fix: "Run with CEEDUMP to expose the original condition token.",
    example: "Job ended with U4093 - CEEDUMP shows underlying CEE3204 (S0C4)" },
  { code: "Custom SUBSYS", title: "CUSTOM SUBSYSTEM RC", category: "CUSTOM", severity: "ERROR",
    description: "Installation-written subsystem returned a non-zero condition code.",
    cause: "Subsystem-specific error; meaning defined by the installation.",
    fix: "Consult site documentation; check subsystem log datasets.",
    example: "Subsystem MYSS returned RC=12 - inventory file lock not released" },
  { code: "SAP MZ", title: "SAP ON DB2 z/OS ERROR", category: "ERP", severity: "ERROR",
    description: "SAP ABAP runtime detected a database error on DB2 for z/OS.",
    cause: "DB2 SQLCODE returned during SAP transaction (commonly -911 or -805).",
    fix: "Check SM21 system log and ST22 dump in SAP for the SQLCODE detail.",
    example: "DBIF_RSQL_SQL_ERROR  SQLCODE -911 deadlock in transaction ZCUST" },
  { code: "FIS COBOL ERR", title: "BANKING PACKAGE ERROR", category: "BANKING", severity: "ERROR",
    description: "Banking package (FIS, Fiserv, Jack Henry) reported a business-rule error.",
    cause: "Account not found, invalid transaction code, or daily cutoff exceeded.",
    fix: "Refer to package message guide; reverse failed transaction.",
    example: "BANK-ERR: ACCOUNT NOT FOUND FOR TRANS-CODE 200" },
  { code: "INSURE PKG", title: "INSURANCE APP ERROR", category: "INSURANCE", severity: "ERROR",
    description: "Insurance core system reported a policy/claim processing error.",
    cause: "Policy in non-active state, missing rider, or premium calculation failure.",
    fix: "Open policy in CRM; verify state and amend if needed.",
    example: "POL-ERR: RIDER R-145 MISSING ON POLICY P-123456" },
  { code: "RES SYSTEM", title: "RESERVATION SYSTEM ERROR", category: "AIRLINE/RES", severity: "ERROR",
    description: "Airline or hotel reservation system rejected a transaction.",
    cause: "Inventory closed, PNR locked, or duplicate booking.",
    fix: "Check inventory state and PNR lock holder; retry after release.",
    example: "RES-ERR: PNR LOCKED BY AGENT A1234 - cannot modify" },
  { code: "STORED PROC ABEND", title: "DB2 STORED PROC FAILURE", category: "STORED PROC", severity: "ERROR",
    description: "Externally-stored procedure abended inside DB2 (WLM stored proc address space).",
    cause: "S0C7 in stored proc, SQLCODE error inside proc, or SP environment issue.",
    fix: "Review WLM SP address space log; check SP source code; reapply COMPILE/BIND.",
    example: "DSNUPRC0 PROC USER1.MYPROC ABEND S0C7 IN WLM-SPAS" },
  { code: "INSTALL EXIT", title: "INSTALLATION EXIT FAILURE", category: "EXIT", severity: "ERROR",
    description: "An installation exit (IEFUSI, IEFACTRT, IEAVMXIT, etc.) failed.",
    cause: "Exit code has a bug, or returned non-zero unexpectedly.",
    fix: "Locate exit module in load library; review source; reapply after fix.",
    example: "IEFUSI exit returned RC=8 - rejected job submission" },
  { code: "BTCH FRAMEWORK", title: "BATCH FRAMEWORK MSG", category: "FRAMEWORK", severity: "ERROR",
    description: "In-house batch framework issued a controlled-failure message.",
    cause: "Framework detected unrecoverable state — bad checkpoint, parm file error, etc.",
    fix: "Refer to framework manual; restart per recovery procedure.",
    example: "BTCH-FW: CHECKPOINT FILE CORRUPT - run RECOVER step before retry" },
  { code: "MQGW INT", title: "MQ GATEWAY INTEGRATION ERROR", category: "INTEGRATION", severity: "ERROR",
    description: "MQ gateway / B2B bridge could not deliver a message.",
    cause: "Format mismatch, schema validation failure, or partner endpoint down.",
    fix: "Check partner queue depth; review MQ error log; validate message against schema.",
    example: "MQGW-ERR: PARTNER QM QM_PRT01 NOT REACHABLE - msg moved to BACKOUT" }
];
